version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo-db:27017/cs308db

  frontend:
    build: .
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: